// This file is auto-generated by @hey-api/openapi-ts

export type AdapterCapability = {
    name: string;
    version?: (string | null);
    available: boolean;
    reason?: (string | null);
    classifications?: Array<PageClassification>;
};

export type ApiKeyCreated = {
    id: string;
    name: string;
    key_prefix: string;
    created_at: string;
    last_used_at: (string | null);
    revoked_at: (string | null);
    api_key: string;
};

export type ApiKeyCreateRequest = {
    name: string;
};

export type ApiKeyMetadata = {
    id: string;
    name: string;
    key_prefix: string;
    created_at: string;
    last_used_at: (string | null);
    revoked_at: (string | null);
};

export type AttemptStatus = 'succeeded' | 'low_confidence' | 'failed' | 'timeout' | 'unavailable';

export type AuditEvent = {
    event_id?: string;
    event_type: string;
    actor_id?: (string | null);
    occurred_at?: string;
    details?: {
        [key: string]: unknown;
    };
};

export type BlogPostCreate = {
    title: string;
    slug: string;
    summary?: (string | null);
    content: string;
    tags?: (string | null);
    is_published?: boolean;
};

export type BlogPostPublic = {
    title: string;
    slug: string;
    summary?: (string | null);
    content: string;
    tags?: (string | null);
    is_published?: boolean;
    id: string;
    author_id: string;
    created_at: string;
    updated_at: string;
};

export type BlogPostsPublic = {
    data: Array<BlogPostPublic>;
    count: number;
};

export type BlogPostUpdate = {
    title?: (string | null);
    summary?: (string | null);
    content?: (string | null);
    tags?: (string | null);
    is_published?: (boolean | null);
};

export type Body_contract_extractions_create_contract_extraction = {
    file: (Blob | File);
    selected_fields?: Array<(string)>;
};

export type Body_document_extractions_create_document_extraction = {
    file: (Blob | File);
    parser?: (string | null);
};

export type Body_document_extractions_create_programmatic_document_extraction = {
    file: (Blob | File);
    parser?: (string | null);
};

export type Body_files_process_document_invoice = {
    file: (Blob | File);
};

export type Body_gptfiles_ocr_endpoint = {
    file?: ((Blob | File) | null);
};

export type Body_gptfiles_ocr_json_endpoint = {
    file?: ((Blob | File) | null);
};

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type Body_profile_upload_profile_image = {
    file: (Blob | File);
};

export type Body_uploadfiles_upload_file = {
    file: (Blob | File);
};

export type Body_uploadfiles_upload_file_ts = {
    file: (Blob | File);
};

export type Body_uploadfiles_upload_file_tspp = {
    file: (Blob | File);
};

export type BoundingBox = {
    left: number;
    top: number;
    right: number;
    bottom: number;
};

export type CapabilityResponse = {
    adapters: Array<AdapterCapability>;
    supported_extensions: Array<(string)>;
    max_upload_bytes: number;
    max_pages: number;
    retry_limits: {
        [key: string]: (number);
    };
    storage_provider?: string;
    execution_backend?: string;
    modal_enabled?: boolean;
};

export type ClassificationSignals = {
    native_text_characters?: number;
    native_text_density?: (number | null);
    raster_coverage?: (number | null);
    replacement_character_ratio?: (number | null);
    formula_score?: number;
    complex_layout_score?: number;
    scientific_score?: number;
    rotation_degrees?: number;
    reasons?: Array<(string)>;
};

/**
 * One row of the persisted table view.
 *
 * Carries both halves so the table can show the **effective** value and still mark
 * which cells a human supplied: ``fields`` is the untouched machine output and
 * ``verified_values`` the human overlay.
 */
export type ContractFieldRecordRow = {
    extraction_id: string;
    document_id: string;
    source_name: string;
    fields: ContractFields;
    selected_fields?: Array<(string)>;
    extraction_status: ExtractionStatus;
    unresolved_fields?: Array<UnresolvedField>;
    verified_values?: {
        [key: string]: (string);
    };
    verified_by?: (string | null);
    verified_at?: (string | null);
    created_at?: string;
};

/**
 * The response for one extraction: the ten keys plus everything around them.
 *
 * The right-hand JSON pane renders ``fields`` only. A ``needs_verification``
 * result is a business outcome, not a transport error — it is persisted and
 * returned with HTTP 200 like any other, because the row is what the human works
 * from.
 */
export type ContractFieldResult = {
    extraction_id: string;
    document_id: string;
    fields: ContractFields;
    selected_fields?: Array<(string)>;
    extraction_status: ExtractionStatus;
    unresolved_fields?: Array<UnresolvedField>;
    field_provenance?: Array<FieldProvenance>;
    warnings?: Array<(string)>;
    verified_values?: {
        [key: string]: (string);
    };
    created_at?: string;
};

/**
 * The ten-key JSON contract.
 *
 * One explicit string field per catalogue key, declared in catalogue order, so the
 * serialized payload always has the same ten keys in the same order — for every
 * selection, including none-selected and all-selected. A field that was not
 * selected, not found, or not groundable is ``""``: never ``None``, never absent,
 * never an invented value.
 *
 * The ten names here mirror the ten table columns one-to-one; the module-level
 * consistency check below fails at import if they ever drift from the catalogue.
 */
export type ContractFields = {
    contract_title?: string;
    customer?: string;
    effective_date?: string;
    term_end_date?: string;
    contract_value?: string;
    governing_law?: string;
    payment_terms?: string;
    notice_period?: string;
    renewal_terms?: string;
    termination_clause?: string;
};

/**
 * ``GET /records`` — one owner-scoped page of rows, matching house convention.
 */
export type ContractFieldsPage = {
    data?: Array<ContractFieldRecordRow>;
    count?: number;
};

export type CoordinateSpace = {
    width: number;
    height: number;
    origin?: "top-left";
};

export type DocumentResult = {
    document_id?: string;
    owner_id: string;
    source: SourceMetadata;
    status?: DocumentStatus;
    extraction_fingerprint?: (string | null);
    reused_extraction?: boolean;
    pages?: Array<PageResult>;
    created_at?: string;
    updated_at?: string;
    revision?: number;
};

export type DocumentStatus = 'queued' | 'classifying' | 'extracting' | 'fallback' | 'needs_review' | 'approved' | 'rejected' | 'failed' | 'cancelled';

export type ExtractedElement = {
    element_id: string;
    type?: 'paragraph' | 'heading' | 'table' | 'table_cell' | 'formula' | 'list_item' | 'image_description' | 'field' | 'other';
    text: string;
    reviewed_text?: (string | null);
    bounding_box?: (BoundingBox | null);
    coordinate_space?: (CoordinateSpace | null);
    reading_order: number;
    confidence?: (number | null);
    confidence_source?: (string | null);
    model_derived?: boolean;
    source_block_number?: (number | null);
    source_paragraph_number?: (number | null);
    source_line_number?: (number | null);
    source_word_number?: (number | null);
};

export type type = 'paragraph' | 'heading' | 'table' | 'table_cell' | 'formula' | 'list_item' | 'image_description' | 'field' | 'other';

export type ExtractionAttempt = {
    parser: string;
    version: string;
    run_id?: string;
    status: AttemptStatus;
    confidence?: (number | null);
    quality_signals?: Array<QualitySignal>;
    error_code?: (string | null);
    error_message?: (string | null);
    retryable?: boolean;
    raw_output_ref?: (string | null);
    provider?: (string | null);
    model?: (string | null);
    prompt_version?: (string | null);
    started_at?: string;
    completed_at?: string;
};

export type ExtractionCandidate = {
    candidate_id?: string;
    parser: ParserSelection;
    confidence?: (number | null);
    confidence_source?: (string | null);
    quality_passed?: boolean;
    elements?: Array<ExtractedElement>;
    warnings?: Array<(string)>;
    created_at?: string;
};

export type ExtractionSnapshot = {
    snapshot_id?: string;
    parser_run_id?: (string | null);
    reason: string;
    elements?: Array<ExtractedElement>;
    warnings?: Array<(string)>;
    captured_at?: string;
};

/**
 * Outcome of one field extraction.
 *
 * Mirrors the existing pipeline's review vocabulary (``PageStatus`` /
 * ``ReviewStatus``) rather than inventing a parallel one.
 */
export type ExtractionStatus = 'complete' | 'needs_verification' | 'verified' | 'rejected';

/**
 * ``GET /fields`` — the schema, served so the frontend never hardcodes a copy.
 */
export type FieldCatalogueResponse = {
    fields?: Array<FieldDefinition>;
    default_fields?: Array<(string)>;
};

/**
 * One catalogue entry. Frozen — the schema is fixed at import time.
 */
export type FieldDefinition = {
    key: string;
    label: string;
    description: string;
    value_format: ValueFormat;
    default_selected: boolean;
};

/**
 * Where a non-blank value came from. Blank values carry no provenance.
 */
export type FieldProvenance = {
    field_key: string;
    page_number: number;
    source_element_ids: Array<(string)>;
    grounding_status: GroundingStatus;
    confidence?: (number | null);
};

export type GroundingStatus = 'grounded' | 'grounded_with_normalization' | 'needs_review' | 'rejected_invalid_reference' | 'rejected_ungrounded' | 'rejected_sensitive_mismatch' | 'rejected_overlap';

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type ItemCreate = {
    title: string;
    description?: (string | null);
};

export type ItemPublic = {
    title: string;
    description?: (string | null);
    id: string;
    owner_id: string;
};

export type ItemsPublic = {
    data: Array<ItemPublic>;
    count: number;
};

export type ItemUpdate = {
    title?: (string | null);
    description?: (string | null);
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type OCRJsonResponse = {
    document_type: string;
    data: {
        [key: string]: unknown;
    };
};

export type OCRResponse = {
    text: string;
};

export type PageClassification = 'digital' | 'scanned' | 'formula_heavy' | 'complex_layout' | 'unknown';

export type PageResult = {
    page_number: number;
    page_status?: PageStatus;
    confidence?: (number | null);
    confidence_source?: (string | null);
    classification?: PageClassification;
    classification_signals?: ClassificationSignals;
    routing_reasons?: Array<(string)>;
    selected_parser?: (ParserSelection | null);
    attempts?: Array<ExtractionAttempt>;
    elements?: Array<ExtractedElement>;
    semantic_result?: ({
    [key: string]: unknown;
} | null);
    candidates?: Array<ExtractionCandidate>;
    selected_candidate_id?: (string | null);
    extraction_history?: Array<ExtractionSnapshot>;
    warnings?: Array<(string)>;
    review?: ReviewState;
    audit_events?: Array<AuditEvent>;
};

export type PageReviewRequest = {
    action: 'save' | 'approve' | 'reject';
    elements?: Array<ReviewElementUpdate>;
    note?: (string | null);
};

export type action = 'save' | 'approve' | 'reject';

export type PageStatus = 'pending' | 'extracting' | 'needs_review' | 'approved' | 'rejected' | 'manual_review_required' | 'failed';

export type ParserSelection = {
    name: string;
    version: string;
    run_id: string;
    rationale: string;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

/**
 * Public metadata about the headshot — lets the page decide whether to
 * render the photo or the initials placeholder, without fetching bytes.
 */
export type ProfileImageMeta = {
    has_image: boolean;
    content_type?: (string | null);
    updated_at?: (string | null);
};

export type QualitySignal = {
    name: string;
    passed?: (boolean | null);
    value?: (number | string | boolean | null);
    threshold?: (number | string | boolean | null);
    detail?: (string | null);
};

export type ReprocessRequest = {
    parser?: (string | null);
    reason: string;
};

export type ReviewElementUpdate = {
    element_id: string;
    reviewed_text: string;
};

export type ReviewState = {
    status?: ReviewStatus;
    reviewer_id?: (string | null);
    reviewed_at?: (string | null);
};

export type ReviewStatus = 'pending' | 'in_progress' | 'approved' | 'rejected';

export type SourceMetadata = {
    source_name: string;
    source_sha256: string;
    media_type: string;
    size_bytes: number;
    page_count: number;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

/**
 * One requested field that came back blank, with the reason it did.
 */
export type UnresolvedField = {
    field_key: string;
    reason: UnresolvedReason;
    detail?: (string | null);
};

/**
 * Why a requested field came back blank. Never a generic "failed".
 */
export type UnresolvedReason = 'not_found' | 'ungrounded' | 'normalization_failed' | 'provider_unavailable';

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    request_limit?: number;
    request_count?: number;
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    request_limit: number;
    request_count: number;
    id: string;
};

/**
 * What the signed-in account has left. `unlimited` is true for superusers,
 * in which case `limit` and `remaining` carry no meaning.
 */
export type UserQuota = {
    limit: number;
    used: number;
    remaining: number;
    unlimited: boolean;
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    request_limit?: number;
    request_count?: number;
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

/**
 * How a field's value is normalized before it reaches the JSON and the table.
 */
export type ValueFormat = 'verbatim' | 'organization_name' | 'date_ddmmyyyy' | 'currency_amount';

/**
 * ``PATCH /{extraction_id}/verify`` — mirrors ``PageReviewRequest``.
 *
 * ``values`` accepts requested keys only; an unknown key, or one that was never
 * requested, is a 422. ``approve`` is refused while any unresolved field still has
 * a blank effective value — a human cannot approve an incomplete result.
 */
export type VerificationRequest = {
    action: 'save' | 'approve' | 'reject';
    values?: {
        [key: string]: (string);
    };
    note?: (string | null);
};

export type BlogListPostsData = {
    limit?: number;
    skip?: number;
};

export type BlogListPostsResponse = (BlogPostsPublic);

export type BlogCreatePostData = {
    requestBody: BlogPostCreate;
};

export type BlogCreatePostResponse = (BlogPostPublic);

export type BlogListAllPostsData = {
    limit?: number;
    skip?: number;
};

export type BlogListAllPostsResponse = (BlogPostsPublic);

export type BlogGetPostData = {
    slug: string;
};

export type BlogGetPostResponse = (BlogPostPublic);

export type BlogUpdatePostData = {
    requestBody: BlogPostUpdate;
    slug: string;
};

export type BlogUpdatePostResponse = (BlogPostPublic);

export type BlogDeletePostData = {
    slug: string;
};

export type BlogDeletePostResponse = (Message);

export type ContractExtractionsGetFieldCatalogueResponse = (FieldCatalogueResponse);

export type ContractExtractionsListRecordsData = {
    extractionStatus?: (ExtractionStatus | null);
    limit?: number;
    skip?: number;
};

export type ContractExtractionsListRecordsResponse = (ContractFieldsPage);

export type ContractExtractionsCreateContractExtractionData = {
    formData: Body_contract_extractions_create_contract_extraction;
};

export type ContractExtractionsCreateContractExtractionResponse = (ContractFieldResult);

export type ContractExtractionsGetContractExtractionData = {
    extractionId: string;
};

export type ContractExtractionsGetContractExtractionResponse = (ContractFieldResult);

export type ContractExtractionsVerifyContractExtractionData = {
    extractionId: string;
    requestBody: VerificationRequest;
};

export type ContractExtractionsVerifyContractExtractionResponse = (ContractFieldResult);

export type ContractExtractionsGetContractExtractionSourceData = {
    extractionId: string;
};

export type ContractExtractionsGetContractExtractionSourceResponse = (unknown);

export type DocumentExtractionsGetCapabilitiesResponse = (CapabilityResponse);

export type DocumentExtractionsCreateDocumentExtractionData = {
    formData: Body_document_extractions_create_document_extraction;
};

export type DocumentExtractionsCreateDocumentExtractionResponse = (DocumentResult);

export type DocumentExtractionsListDocumentExtractionApiKeysResponse = (Array<ApiKeyMetadata>);

export type DocumentExtractionsCreateDocumentExtractionApiKeyData = {
    requestBody: ApiKeyCreateRequest;
};

export type DocumentExtractionsCreateDocumentExtractionApiKeyResponse = (ApiKeyCreated);

export type DocumentExtractionsRevokeDocumentExtractionApiKeyData = {
    keyId: string;
};

export type DocumentExtractionsRevokeDocumentExtractionApiKeyResponse = (void);

export type DocumentExtractionsRotateDocumentExtractionApiKeyData = {
    keyId: string;
};

export type DocumentExtractionsRotateDocumentExtractionApiKeyResponse = (ApiKeyCreated);

export type DocumentExtractionsCreateProgrammaticDocumentExtractionData = {
    formData: Body_document_extractions_create_programmatic_document_extraction;
    xApiKey?: (string | null);
};

export type DocumentExtractionsCreateProgrammaticDocumentExtractionResponse = (DocumentResult);

export type DocumentExtractionsGetProgrammaticDocumentExtractionData = {
    documentId: string;
    xApiKey?: (string | null);
};

export type DocumentExtractionsGetProgrammaticDocumentExtractionResponse = (DocumentResult);

export type DocumentExtractionsGetDocumentExtractionData = {
    documentId: string;
};

export type DocumentExtractionsGetDocumentExtractionResponse = (DocumentResult);

export type DocumentExtractionsDeleteDocumentExtractionData = {
    documentId: string;
};

export type DocumentExtractionsDeleteDocumentExtractionResponse = (void);

export type DocumentExtractionsExportDocumentExtractionData = {
    documentId: string;
};

export type DocumentExtractionsExportDocumentExtractionResponse = (unknown);

export type DocumentExtractionsGetDocumentSourceData = {
    documentId: string;
};

export type DocumentExtractionsGetDocumentSourceResponse = (unknown);

export type DocumentExtractionsGetDocumentPagePreviewData = {
    documentId: string;
    pageNumber: number;
};

export type DocumentExtractionsGetDocumentPagePreviewResponse = (unknown);

export type DocumentExtractionsReviewDocumentPageData = {
    documentId: string;
    pageNumber: number;
    requestBody: PageReviewRequest;
};

export type DocumentExtractionsReviewDocumentPageResponse = (PageResult);

export type DocumentExtractionsReprocessDocumentPageData = {
    documentId: string;
    pageNumber: number;
    requestBody: ReprocessRequest;
};

export type DocumentExtractionsReprocessDocumentPageResponse = (PageResult);

export type FilesProcessDocumentInvoiceData = {
    formData: Body_files_process_document_invoice;
};

export type FilesProcessDocumentInvoiceResponse = (unknown);

export type GptfilesOcrEndpointData = {
    formData?: Body_gptfiles_ocr_endpoint;
};

export type GptfilesOcrEndpointResponse = (OCRResponse);

export type GptfilesOcrJsonEndpointData = {
    formData?: Body_gptfiles_ocr_json_endpoint;
};

export type GptfilesOcrJsonEndpointResponse = (OCRJsonResponse);

export type ItemsReadItemsData = {
    limit?: number;
    skip?: number;
};

export type ItemsReadItemsResponse = (ItemsPublic);

export type ItemsCreateItemData = {
    requestBody: ItemCreate;
};

export type ItemsCreateItemResponse = (ItemPublic);

export type ItemsReadItemData = {
    id: string;
};

export type ItemsReadItemResponse = (ItemPublic);

export type ItemsUpdateItemData = {
    id: string;
    requestBody: ItemUpdate;
};

export type ItemsUpdateItemResponse = (ItemPublic);

export type ItemsDeleteItemData = {
    id: string;
};

export type ItemsDeleteItemResponse = (Message);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type OauthOauthLoginData = {
    provider: string;
};

export type OauthOauthLoginResponse = (unknown);

export type OauthOauthCallbackData = {
    code?: (string | null);
    error?: (string | null);
    oauthState?: (string | null);
    provider: string;
    state?: (string | null);
};

export type OauthOauthCallbackResponse = (unknown);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type ProfileGetProfileImageMetaResponse = (ProfileImageMeta);

export type ProfileGetProfileImageResponse = (unknown);

export type ProfileUploadProfileImageData = {
    formData: Body_profile_upload_profile_image;
};

export type ProfileUploadProfileImageResponse = (ProfileImageMeta);

export type ProfileDeleteProfileImageResponse = (Message);

export type ProfileChatProfileChatResponse = (unknown);

export type UploadfilesUploadFileTsData = {
    formData: Body_uploadfiles_upload_file_ts;
};

export type UploadfilesUploadFileTsResponse = (unknown);

export type UploadfilesUploadFileTsppData = {
    formData: Body_uploadfiles_upload_file_tspp;
};

export type UploadfilesUploadFileTsppResponse = (unknown);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersReadUserQuotaResponse = (UserQuota);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);