import type { Course } from "./types"

export const MOCK_COURSES: Course[] = [
  {
    id: "1",
    title: "Applied Data Science & Machine Learning",
    category: "Data Science",
    description:
      "Master the full data science pipeline from exploratory analysis to deploying ML models in production. Hands-on projects using real-world datasets from fintech and healthcare.",
    highlights: ["Python & R", "Scikit-learn & TensorFlow", "Capstone Project"],
    rating: 4.8,
    reviewCount: 1243,
    cost: 45000,
    costType: "total",
    currency: "INR",
    duration: "12 months",
    durationMonths: 12,
    mode: "hybrid",
    level: "intermediate",
    enrollmentOpen: true,
    nextStartDate: "2026-03-15",
    scholarshipAvailable: true,
    college: {
      id: "c1",
      name: "IIT Bangalore Extension",
      type: "institute",
      location: "Koramangala, Bangalore",
      city: "Bangalore",
      rating: 4.9,
      reviewCount: 5200,
      accredited: true,
      distanceKm: 1.2,
    },
  },
  {
    id: "2",
    title: "Full-Stack Web Development Bootcamp",
    category: "Web Development",
    description:
      "From zero to job-ready in 6 months. Cover React, Node.js, PostgreSQL, and deploy full applications on cloud infrastructure. Includes career placement support and mock interviews.",
    highlights: ["React & Next.js", "Node.js & Express", "Job Guarantee"],
    rating: 4.6,
    reviewCount: 892,
    cost: 8500,
    costType: "per-month",
    currency: "INR",
    duration: "6 months",
    durationMonths: 6,
    mode: "online",
    level: "beginner",
    enrollmentOpen: true,
    nextStartDate: "2026-03-01",
    scholarshipAvailable: false,
    college: {
      id: "c2",
      name: "Masai School",
      type: "bootcamp",
      location: "HSR Layout, Bangalore",
      city: "Bangalore",
      rating: 4.4,
      reviewCount: 3100,
      accredited: false,
      distanceKm: 3.7,
    },
  },
  {
    id: "3",
    title: "MBA in Digital Marketing & Analytics",
    category: "Marketing",
    description:
      "Two-year MBA blending traditional marketing theory with modern digital channels, SEO/SEM, social media strategy, and analytics platforms. Dual specialisation available.",
    highlights: ["Google Analytics Certified", "Live Brand Projects", "Industry Mentorship"],
    rating: 4.5,
    reviewCount: 567,
    cost: 280000,
    costType: "total",
    currency: "INR",
    duration: "2 years",
    durationMonths: 24,
    mode: "offline",
    level: "advanced",
    enrollmentOpen: false,
    nextStartDate: "2026-06-01",
    scholarshipAvailable: true,
    college: {
      id: "c3",
      name: "Christ University",
      type: "university",
      location: "Hosur Road, Bangalore",
      city: "Bangalore",
      rating: 4.2,
      reviewCount: 8900,
      accredited: true,
      distanceKm: 5.1,
    },
  },
  {
    id: "4",
    title: "UI/UX Design Professional Certificate",
    category: "Design",
    description:
      "Industry-aligned design curriculum covering user research, wireframing, Figma prototyping, and design systems. Build a portfolio of 5 end-to-end projects reviewed by senior designers.",
    highlights: ["Figma & Adobe XD", "Portfolio of 5 Projects", "Weekly Critiques"],
    rating: 4.7,
    reviewCount: 2100,
    cost: 32000,
    costType: "total",
    currency: "INR",
    duration: "8 months",
    durationMonths: 8,
    mode: "online",
    level: "beginner",
    enrollmentOpen: true,
    nextStartDate: "2026-03-10",
    scholarshipAvailable: true,
    college: {
      id: "c4",
      name: "Interaction Design Foundation",
      type: "institute",
      location: "Online",
      city: "Online",
      rating: 4.8,
      reviewCount: 42000,
      accredited: true,
      distanceKm: 0,
    },
  },
  {
    id: "5",
    title: "AI & Deep Learning Specialization",
    category: "AI/ML",
    description:
      "Rigorous deep learning curriculum from fundamentals to cutting-edge architectures. Covers CNNs, RNNs, transformers, and hands-on LLM fine-tuning with cloud GPU access.",
    highlights: ["PyTorch & JAX", "LLM Fine-tuning", "Research Paper Reviews"],
    rating: 4.9,
    reviewCount: 3400,
    cost: 65000,
    costType: "total",
    currency: "INR",
    duration: "9 months",
    durationMonths: 9,
    mode: "online",
    level: "advanced",
    enrollmentOpen: true,
    nextStartDate: "2026-04-01",
    scholarshipAvailable: false,
    college: {
      id: "c5",
      name: "upGrad × IIIT Hyderabad",
      type: "institute",
      location: "Online / Hyderabad",
      city: "Hyderabad",
      rating: 4.6,
      reviewCount: 12000,
      accredited: true,
      distanceKm: 12.4,
    },
  },
  {
    id: "6",
    title: "B.Com Business Analytics",
    category: "Business",
    description:
      "Three-year undergraduate program combining core commerce subjects with business intelligence, data visualisation, and strategic management. Includes SAP ERP practical training.",
    highlights: ["CFA Foundation Prep", "SAP ERP Practical", "Industry Internship"],
    rating: 4.1,
    reviewCount: 430,
    cost: 95000,
    costType: "per-year",
    currency: "INR",
    duration: "3 years",
    durationMonths: 36,
    mode: "offline",
    level: "beginner",
    enrollmentOpen: false,
    nextStartDate: "2026-07-15",
    scholarshipAvailable: true,
    college: {
      id: "c6",
      name: "Jain (Deemed) University",
      type: "university",
      location: "JC Road, Bangalore",
      city: "Bangalore",
      rating: 3.9,
      reviewCount: 15000,
      accredited: true,
      distanceKm: 7.8,
    },
  },
  {
    id: "7",
    title: "Python for Data Science & AI",
    category: "Data Science",
    description:
      "Beginner-friendly introduction to Python programming with immediate applications in data manipulation, visualisation, and basic machine learning models. Self-paced with lifetime access.",
    highlights: ["Pandas & NumPy", "Matplotlib & Seaborn", "5 Mini Projects"],
    rating: 4.5,
    reviewCount: 6700,
    cost: 4999,
    costType: "total",
    currency: "INR",
    duration: "3 months",
    durationMonths: 3,
    mode: "online",
    level: "beginner",
    enrollmentOpen: true,
    nextStartDate: "2026-03-01",
    scholarshipAvailable: false,
    college: {
      id: "c7",
      name: "Coursera × IIT Bombay",
      type: "institute",
      location: "Online",
      city: "Online",
      rating: 4.7,
      reviewCount: 89000,
      accredited: true,
      distanceKm: 0,
    },
  },
  {
    id: "8",
    title: "Digital Marketing: SEO to Performance",
    category: "Marketing",
    description:
      "Practical end-to-end digital marketing training: organic SEO, paid search ads, email automation, and conversion rate optimisation using live ad budgets on real campaigns.",
    highlights: ["Google Ads Certified", "Live Campaign Budget", "Agency Internship"],
    rating: 4.3,
    reviewCount: 1580,
    cost: 18000,
    costType: "total",
    currency: "INR",
    duration: "4 months",
    durationMonths: 4,
    mode: "hybrid",
    level: "intermediate",
    enrollmentOpen: true,
    nextStartDate: "2026-03-20",
    scholarshipAvailable: false,
    college: {
      id: "c8",
      name: "NIIT Digital",
      type: "institute",
      location: "MG Road, Bangalore",
      city: "Bangalore",
      rating: 4.0,
      reviewCount: 7200,
      accredited: false,
      distanceKm: 2.9,
    },
  },
  {
    id: "9",
    title: "Advanced React & Frontend System Design",
    category: "Web Development",
    description:
      "Senior-level frontend engineering covering React internals, performance optimisation, micro-frontends, and designing scalable frontend architectures for high-traffic applications.",
    highlights: ["React 19 Internals", "Micro-frontend Architecture", "System Design Interviews"],
    rating: 4.7,
    reviewCount: 980,
    cost: 28000,
    costType: "total",
    currency: "INR",
    duration: "5 months",
    durationMonths: 5,
    mode: "online",
    level: "advanced",
    enrollmentOpen: true,
    nextStartDate: "2026-03-05",
    scholarshipAvailable: false,
    college: {
      id: "c9",
      name: "Scaler Academy",
      type: "bootcamp",
      location: "BTM Layout, Bangalore",
      city: "Bangalore",
      rating: 4.5,
      reviewCount: 18000,
      accredited: false,
      distanceKm: 4.2,
    },
  },
  {
    id: "10",
    title: "Product Management Certification",
    category: "Business",
    description:
      "Become a PM ready to drive product strategy at tech companies. Covers product discovery, roadmapping, metrics-driven decision making, and executive stakeholder management.",
    highlights: ["Live Product Sprints", "VC Pitch Simulation", "LinkedIn Optimisation"],
    rating: 4.4,
    reviewCount: 2300,
    cost: 55000,
    costType: "total",
    currency: "INR",
    duration: "6 months",
    durationMonths: 6,
    mode: "hybrid",
    level: "intermediate",
    enrollmentOpen: true,
    nextStartDate: "2026-04-01",
    scholarshipAvailable: true,
    college: {
      id: "c10",
      name: "ISB Executive Education",
      type: "institute",
      location: "Online / Hyderabad",
      city: "Hyderabad",
      rating: 4.8,
      reviewCount: 24000,
      accredited: true,
      distanceKm: 15.6,
    },
  },
  {
    id: "11",
    title: "Generative AI & Prompt Engineering",
    category: "AI/ML",
    description:
      "Hands-on course covering LLM prompting techniques, RAG systems, AI agents, and building production-grade GenAI applications. Access to API credits included.",
    highlights: ["OpenAI & Anthropic APIs", "LangChain & LlamaIndex", "Build 3 AI Apps"],
    rating: 4.8,
    reviewCount: 4100,
    cost: 12000,
    costType: "total",
    currency: "INR",
    duration: "2 months",
    durationMonths: 2,
    mode: "online",
    level: "intermediate",
    enrollmentOpen: true,
    nextStartDate: "2026-03-01",
    scholarshipAvailable: false,
    college: {
      id: "c11",
      name: "DeepLearning.AI",
      type: "institute",
      location: "Online",
      city: "Online",
      rating: 4.9,
      reviewCount: 310000,
      accredited: true,
      distanceKm: 0,
    },
  },
  {
    id: "12",
    title: "Graphic Design & Brand Identity",
    category: "Design",
    description:
      "Studio-style design program covering typography, colour theory, logo design, and complete brand identity systems. Work on real client briefs with a structured portfolio review.",
    highlights: ["Adobe Creative Suite", "Real Client Brief", "Portfolio Review"],
    rating: 4.2,
    reviewCount: 670,
    cost: 22000,
    costType: "total",
    currency: "INR",
    duration: "6 months",
    durationMonths: 6,
    mode: "offline",
    level: "beginner",
    enrollmentOpen: true,
    nextStartDate: "2026-04-15",
    scholarshipAvailable: true,
    college: {
      id: "c12",
      name: "Arena Animation",
      type: "institute",
      location: "Indiranagar, Bangalore",
      city: "Bangalore",
      rating: 3.8,
      reviewCount: 4500,
      accredited: false,
      distanceKm: 6.3,
    },
  },
]

export const ALL_CATEGORIES = [
  "Data Science",
  "Web Development",
  "Design",
  "Business",
  "Marketing",
  "AI/ML",
]
